name: my_app
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.2

# Add regular dependencies here.
dependencies:
  retrofit: '>=4.0.0 <5.0.0'
  logger: any  #for logging purpose

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  retrofit_generator: '>=5.0.0 <6.0.0'
  build_runner: '>=2.3.0 <4.0.0' 
  json_serializable: ^6.7.0
